# Generated by Django 4.1.5 on 2023-01-18 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csd', '0023_rename_prd_code_id_invoicedaily_prd_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreReview',
            fields=[
                ('str_rcode', models.BigAutoField(primary_key=True, serialize=False)),
                ('str_img', models.ImageField(upload_to='media/%Y/%m/%d/')),
                ('str_comm', models.CharField(max_length=500)),
                ('str_rate', models.IntegerField(blank=True, null=True)),
                ('str_date', models.DateTimeField(auto_now_add=True)),
                ('str_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csd.store')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Review Data',
                'verbose_name_plural': 'Store Review Data',
                'db_table': 'tbl_str_review',
            },
        ),
    ]
