# Generated by Django 4.1.5 on 2023-01-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storereview',
            name='str_img',
            field=models.ImageField(upload_to='media/%Y%m%d/'),
        ),
    ]
