# Generated by Django 4.1.3 on 2022-11-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32, unique=True)),
                ('user_pw', models.CharField(max_length=128)),
                ('user_name', models.CharField(max_length=16, unique=True)),
                ('user_email', models.EmailField(max_length=128, unique=True)),
                ('user_reg_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Master',
                'verbose_name_plural': 'User Master',
                'db_table': 'tbl_user',
            },
        ),
    ]
