# Generated by Django 4.1.5 on 2023-02-06 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("csd", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product_selling_price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("selling_price", models.IntegerField()),
                ("year", models.DateField()),
                (
                    "product_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="csd.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Dashboard_Table_month_basic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField()),
                ("target_qauntity", models.IntegerField(blank=True, null=True)),
                ("target_sales", models.IntegerField(blank=True, null=True)),
                ("expect_qauntity", models.IntegerField(blank=True, null=True)),
                ("expect_sales", models.IntegerField(blank=True, null=True)),
                (
                    "product_selling_price_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.product_selling_price",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
