# Generated by Django 4.1.3 on 2022-11-17 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('product_code', models.CharField(help_text='Product code', max_length=200, primary_key=True, serialize=False)),
                ('product_code_bystore', models.CharField(help_text='Product store code', max_length=200)),
                ('product_barcode', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('product_detail', models.TextField()),
                ('product_use', models.BooleanField(default=True)),
                ('product_create_time', models.DateTimeField(auto_now_add=True)),
                ('product_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'product_master_data',
            },
        ),
        migrations.CreateModel(
            name='tbl_store',
            fields=[
                ('store_code', models.CharField(help_text='store code', max_length=200, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=200)),
                ('store_district', models.CharField(max_length=200)),
                ('store_city', models.CharField(max_length=200)),
                ('store_address', models.TextField()),
                ('store_detail', models.TextField(blank=True, null=True)),
                ('store_start', models.DateField()),
                ('store_end', models.DateField(blank=True, null=True)),
                ('store_use', models.BooleanField(default=True)),
                ('store_create_time', models.DateTimeField(auto_now_add=True)),
                ('store_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'store_master_data',
            },
        ),
        migrations.CreateModel(
            name='tbl_invoice_daily',
            fields=[
                ('invoice_day_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_day_date', models.DateField()),
                ('invoice_day_save', models.IntegerField()),
                ('invoice_day_buy', models.IntegerField()),
                ('invoice_day_return', models.IntegerField()),
                ('invoice_day_sale', models.IntegerField()),
                ('invoice_day_stock', models.IntegerField()),
                ('invoice_day_create_time', models.DateTimeField(auto_now_add=True)),
                ('invoice_day_updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_day_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csd.tbl_product')),
                ('invoice_day_store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csd.tbl_store')),
            ],
            options={
                'verbose_name_plural': 'daily_row_data',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('file_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_path', models.FileField(upload_to='upload_files/%Y%m%d/')),
                ('file_name', models.CharField(max_length=200)),
                ('file_create_time', models.DateTimeField(auto_now_add=True)),
                ('file_updated_at', models.DateTimeField(auto_now=True)),
                ('file_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'documents_uploaded',
            },
        ),
    ]
