# Generated by Django 4.1.3 on 2022-11-18 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDaily',
            fields=[
                ('data_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('data_path', models.FileField(upload_to='files/%Y%m%d/')),
                ('data_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Daily Data Master',
                'verbose_name_plural': 'Daily Data Master',
                'db_table': 'tbl_data_d',
            },
        ),
        migrations.CreateModel(
            name='InvoiceDaily',
            fields=[
                ('inv_d_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('inv_d_date', models.DateField()),
                ('inv_d_save', models.IntegerField()),
                ('inv_d_buy', models.IntegerField()),
                ('inv_d_return', models.IntegerField()),
                ('inv_d_sale', models.IntegerField()),
                ('inv_d_stock', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Daily Invoice Master',
                'verbose_name_plural': 'Daily Invoice Master',
                'db_table': 'tbl_invoice_d',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prd_code', models.CharField(help_text='Product code', max_length=200, primary_key=True, serialize=False)),
                ('prd_barcode', models.CharField(max_length=200)),
                ('prd_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Product Master',
                'verbose_name_plural': 'Product Master',
                'db_table': 'tbl_product',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('str_code', models.CharField(help_text='store code', max_length=200, primary_key=True, serialize=False)),
                ('str_city', models.CharField(max_length=200)),
                ('str_loc', models.CharField(help_text='store location', max_length=200)),
                ('str_name', models.CharField(max_length=200)),
                ('str_address', models.TextField(blank=True, null=True)),
                ('str_detail', models.TextField(blank=True, null=True)),
                ('str_use', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Store Master',
                'verbose_name_plural': 'Store Master',
                'db_table': 'tbl_store',
            },
        ),
        migrations.RemoveField(
            model_name='tbl_invoice_daily',
            name='invoice_day_product',
        ),
        migrations.RemoveField(
            model_name='tbl_invoice_daily',
            name='invoice_day_store',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='tbl_invoice_daily',
        ),
        migrations.DeleteModel(
            name='tbl_product',
        ),
        migrations.DeleteModel(
            name='tbl_store',
        ),
        migrations.AddField(
            model_name='invoicedaily',
            name='prd_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csd.product'),
        ),
        migrations.AddField(
            model_name='invoicedaily',
            name='str_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csd.store'),
        ),
        migrations.AddField(
            model_name='datadaily',
            name='prd_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csd.product'),
        ),
        migrations.AddField(
            model_name='datadaily',
            name='str_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csd.store'),
        ),
        migrations.AddField(
            model_name='datadaily',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
