# Generated by Django 4.1.3 on 2022-11-22 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csd', '0003_remove_store_str_address_remove_store_str_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedaily',
            old_name='prd_code',
            new_name='inv_prd_code',
        ),
        migrations.RenameField(
            model_name='invoicedaily',
            old_name='str_code',
            new_name='inv_str_code',
        ),
    ]
