# Generated by Django 4.1.3 on 2022-11-23 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csd', '0005_rename_inv_prd_code_invoicedaily_prd_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SumDaily',
            fields=[
                ('sum_d_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('sum_d_date', models.DateField()),
                ('sum_d_save', models.IntegerField()),
                ('sum_d_buy', models.IntegerField()),
                ('sum_d_return', models.IntegerField()),
                ('sum_d_sale', models.IntegerField()),
                ('sum_d_stock', models.IntegerField()),
                ('prd_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csd.product')),
                ('str_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csd.store')),
            ],
            options={
                'verbose_name': 'Daily Sum Data',
                'verbose_name_plural': 'Daily Sum Data',
                'db_table': 'tbl_sum_d',
            },
        ),
    ]
