# Generated by Django 4.1.2 on 2022-11-28 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csd', '0006_sumdaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleDaily',
            fields=[
                ('sale_d_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('sale_d_month', models.DateField()),
                ('sale_d1', models.IntegerField()),
                ('sale_d2', models.IntegerField()),
                ('sale_d3', models.IntegerField()),
                ('sale_d4', models.IntegerField()),
                ('sale_d5', models.IntegerField()),
                ('sale_d6', models.IntegerField()),
                ('sale_d7', models.IntegerField()),
                ('sale_d8', models.IntegerField()),
                ('sale_d9', models.IntegerField()),
                ('sale_d10', models.IntegerField()),
                ('sale_d11', models.IntegerField()),
                ('sale_d12', models.IntegerField()),
                ('sale_d13', models.IntegerField()),
                ('sale_d14', models.IntegerField()),
                ('sale_d15', models.IntegerField()),
                ('sale_d16', models.IntegerField()),
                ('sale_d17', models.IntegerField()),
                ('sale_d18', models.IntegerField()),
                ('sale_d19', models.IntegerField()),
                ('sale_d20', models.IntegerField()),
                ('sale_d21', models.IntegerField()),
                ('sale_d22', models.IntegerField()),
                ('sale_d23', models.IntegerField()),
                ('sale_d24', models.IntegerField()),
                ('sale_d25', models.IntegerField()),
                ('sale_d26', models.IntegerField()),
                ('sale_d27', models.IntegerField()),
                ('sale_d28', models.IntegerField()),
                ('sale_d29', models.IntegerField()),
                ('sale_d30', models.IntegerField()),
                ('sale_d31', models.IntegerField()),
                ('prd_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csd.product')),
                ('str_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csd.store')),
            ],
            options={
                'verbose_name': 'Daily Sale Data',
                'verbose_name_plural': 'Daily Sale Data',
                'db_table': 'tbl_sale_d',
            },
        ),
    ]
