# Generated by Django 4.1.2 on 2022-11-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csd', '0007_saledaily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledaily',
            name='sale_d_month',
            field=models.IntegerField(),
        ),
    ]
