# Generated by Django 4.1.2 on 2022-12-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csd', '0008_alter_saledaily_sale_d_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedaily',
            name='inv_d_buy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedaily',
            name='inv_d_return',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedaily',
            name='inv_d_sale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedaily',
            name='inv_d_save',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedaily',
            name='inv_d_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SaleDaily',
        ),
    ]
