# Generated by Django 4.1.3 on 2022-12-05 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csd', '0009_alter_invoicedaily_inv_d_buy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sumdaily',
            name='str_code',
        ),
    ]
