# Generated by Django 4.1.3 on 2022-12-05 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csd', '0010_remove_sumdaily_str_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadaily',
            name='str_code',
        ),
        migrations.RemoveField(
            model_name='invoicedaily',
            name='str_code',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
