# Generated by Django 4.1.3 on 2022-12-05 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csd', '0011_remove_datadaily_str_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('str_code', models.CharField(help_text='store code', max_length=200, primary_key=True, serialize=False)),
                ('str_city', models.CharField(max_length=200)),
                ('str_loc', models.CharField(help_text='store location', max_length=200)),
                ('str_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Store Master',
                'verbose_name_plural': 'Store Master',
                'db_table': 'tbl_store',
            },
        ),
        migrations.AddField(
            model_name='datadaily',
            name='str_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csd.store'),
        ),
        migrations.AddField(
            model_name='invoicedaily',
            name='str_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csd.store'),
        ),
        migrations.AddField(
            model_name='sumdaily',
            name='str_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csd.store'),
        ),
    ]
