# Generated by Django 4.1.3 on 2022-12-05 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csd', '0012_store_datadaily_str_code_invoicedaily_str_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sumdaily',
            name='str_code',
        ),
    ]
