# Generated by Django 4.1.3 on 2022-12-20 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csd', '0019_invoicedaily_prd_code_invoicedaily_str_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedaily',
            old_name='prd_code',
            new_name='prd_code_id',
        ),
        migrations.RenameField(
            model_name='invoicedaily',
            old_name='str_code',
            new_name='str_code_id',
        ),
    ]
