# Generated by Django 4.1.3 on 2022-12-20 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csd', '0020_rename_prd_code_invoicedaily_prd_code_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceDaily',
        ),
    ]
