# Generated by Django 4.1.3 on 2022-12-20 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csd', '0021_delete_invoicedaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDaily',
            fields=[
                ('inv_d_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('inv_d_date', models.DateField()),
                ('inv_d_save', models.IntegerField(blank=True, null=True)),
                ('inv_d_buy', models.IntegerField(blank=True, null=True)),
                ('inv_d_return', models.IntegerField(blank=True, null=True)),
                ('inv_d_sale', models.IntegerField(blank=True, null=True)),
                ('inv_d_stock', models.IntegerField(blank=True, null=True)),
                ('prd_code_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csd.product')),
                ('str_code_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csd.store')),
            ],
            options={
                'verbose_name': 'Daily Invoice Master',
                'verbose_name_plural': 'Daily Invoice Master',
                'db_table': 'tbl_invoice_d',
            },
        ),
    ]
