# Generated by Django 4.1.3 on 2022-12-20 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csd', '0022_invoicedaily'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedaily',
            old_name='prd_code_id',
            new_name='prd_code',
        ),
        migrations.RenameField(
            model_name='invoicedaily',
            old_name='str_code_id',
            new_name='str_code',
        ),
    ]
