# Generated by Django 4.1.5 on 2023-03-22 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csd', '0023_rename_prd_code_id_invoicedaily_prd_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceMonthly',
            fields=[
                ('inv_m_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('inv_m_date', models.DateField()),
                ('inv_m_save', models.IntegerField(blank=True, null=True)),
                ('inv_m_buy', models.IntegerField(blank=True, null=True)),
                ('inv_m_return', models.IntegerField(blank=True, null=True)),
                ('inv_m_sale', models.IntegerField(blank=True, null=True)),
                ('inv_m_stock', models.IntegerField(blank=True, null=True)),
                ('prd_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csd.product')),
                ('str_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csd.store')),
            ],
            options={
                'verbose_name': 'Monthly Invoice Master',
                'verbose_name_plural': 'Monthly Invoice Master',
                'db_table': 'tbl_invoice_m',
            },
        ),
        migrations.DeleteModel(
            name='DataDaily',
        ),
    ]
