# Generated by Django 4.1.5 on 2023-03-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csd', '0024_invoicemonthly_delete_datadaily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedaily',
            name='inv_d_buy',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedaily',
            name='inv_d_return',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedaily',
            name='inv_d_sale',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedaily',
            name='inv_d_save',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedaily',
            name='inv_d_stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
