# Generated by Django 4.1.5 on 2023-03-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csd', '0027_alter_invoicedaily_inv_d_buy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedaily',
            name='inv_d_buy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedaily',
            name='inv_d_return',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedaily',
            name='inv_d_sale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedaily',
            name='inv_d_save',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedaily',
            name='inv_d_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
