# Generated by Django 4.1.3 on 2022-12-05 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('csd', '0011_remove_datadaily_str_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('str_code', models.CharField(help_text='store code', max_length=200, primary_key=True, serialize=False)),
                ('str_city', models.CharField(max_length=200)),
                ('str_loc', models.CharField(help_text='store location', max_length=200)),
                ('str_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Store Master',
                'verbose_name_plural': 'Store Master',
                'db_table': 'tbl_store',
            },
        ),
        migrations.CreateModel(
            name='SumMonthly',
            fields=[
                ('sum_m_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('sum_m_date', models.DateField()),
                ('sum_m_save', models.IntegerField()),
                ('sum_m_buy', models.IntegerField()),
                ('sum_m_return', models.IntegerField()),
                ('sum_m_sale', models.IntegerField()),
                ('sum_m_stock', models.IntegerField()),
                ('prd_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csd.product')),
                ('str_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csm.store')),
            ],
            options={
                'verbose_name': 'Monthly Sum Data',
                'verbose_name_plural': 'Monthly Sum Data',
                'db_table': 'tbl_sum_m',
            },
        ),
        migrations.CreateModel(
            name='DataMonthly',
            fields=[
                ('data_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('data_path', models.FileField(upload_to='files/%Y%m%d/')),
                ('data_name', models.CharField(max_length=200)),
                ('prd_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csd.product')),
                ('str_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csm.store')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Data Master',
                'verbose_name_plural': 'Monthly Data Master',
                'db_table': 'tbl_data_m',
            },
        ),
    ]
