# Generated by Django 4.1.3 on 2022-12-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0003_summonthly_sum_m_sale_err_summonthly_sum_m_sale_ttl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summonthly',
            name='sum_m_sale_err',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summonthly',
            name='sum_m_sale_ttl',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
