# Generated by Django 4.1.2 on 2022-12-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0004_alter_summonthly_sum_m_sale_err_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summonthly',
            name='str_code',
        ),
    ]
