# Generated by Django 4.1.2 on 2022-12-06 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csd', '0013_remove_sumdaily_str_code'),
        ('csm', '0005_remove_summonthly_str_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='summonthly',
            name='str_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csd.store'),
        ),
    ]
