# Generated by Django 4.1.2 on 2022-12-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0006_summonthly_str_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SumMonthly',
        ),
    ]
