# Generated by Django 4.1.2 on 2022-12-06 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csd', '0013_remove_sumdaily_str_code'),
        ('csm', '0007_delete_summonthly'),
    ]

    operations = [
        migrations.CreateModel(
            name='SumMonthly',
            fields=[
                ('sum_m_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('sum_m_date', models.DateField()),
                ('sum_m_save', models.IntegerField()),
                ('sum_m_buy', models.IntegerField()),
                ('sum_m_return', models.IntegerField()),
                ('sum_m_sale', models.IntegerField()),
                ('sum_m_stock', models.IntegerField()),
                ('sum_m_sale_ttl', models.FloatField(blank=True, null=True)),
                ('sum_m_sale_err', models.FloatField(blank=True, null=True)),
                ('prd_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csd.product')),
                ('str_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csd.store')),
            ],
            options={
                'verbose_name': 'Monthly Sum Data',
                'verbose_name_plural': 'Monthly Sum Data',
                'db_table': 'tbl_sum_m',
            },
        ),
    ]
