# Generated by Django 4.1.3 on 2022-12-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0008_summonthly'),
    ]

    operations = [
        migrations.AddField(
            model_name='summonthly',
            name='sum_m_stock_mon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
